name: check

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  FORCE_COLOR: 1

permissions: {}

jobs:
  check:
    runs-on: "ubuntu-latest"
    name: "check"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: false

      - name: "Run checks"
        run: |
          ./check.py

      - name: "Run unit tests"
        run: |
          uv run python -m unittest tests/test_mirror.py

      - name: "Run mirror integration test"
        run: |
          uv run python -m unittest tests/test_mirror_integration.py
