name: check

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  FORCE_COLOR: 1

permissions: {}

jobs:
  check:
    runs-on: "ubuntu-latest"
    name: "check"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          enable-cache: false

      - name: "Run checks"
        run: |
          ./check.py

      - name: "Run unit tests"
        run: |
          uv run python -m unittest tests/test_mirror.py

      - name: "Run mirror integration test"
        run: |
          uv run python -m unittest tests/test_mirror_integration.py
